[package]
name = "nlab-listary-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.20.2"
# reqwest = { version = "0.12.23", features = ["blocking", "json"] }
scraper = "0.24.0"
walkdir = "2.5.0"
# tokio = { version = "1.47.1", features = ["full"] }
