[application]
name = "nlab-listary-ui"
default_platform = "desktop"
platform = "desktop"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Nlab Listary"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]