[application]
name = "nlab-listary-ui"
default_platform = "desktop"
platform = "desktop"
out_dir = "dist"
asset_dir = "assets"

[bundle]
identifier = "com.nlab.listary"
publisher = "songever"
icon = ["src-tauri/icons/icon.png"]

