[application]
name = "nlab-listary-ui"
default_platform = "web"
out_dir = "target/dx/nlab-listary-ui/debug/web/public"
asset_dir = "assets"

[bundle]
identifier = "com.nlab.listary"
publisher = "songever"
icon = ["src-tauri/icons/icon.png"]

